[build]
command = "npm run build"
publish = "build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[build.environment]
REACT_APP_API_URL = "https://quant-finance-backend.onrender.com/api"